<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-09-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semilleros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='contacto',
            field=models.CharField(default='Sin contacto', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semillero',
            name='docenteCoordinador',
            field=models.CharField(default='Sin docente', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semillero',
            name='programa',
            field=models.CharField(default='Sin programa', max_length=255),
            preserve_default=False,
        ),
    ]
=======
# Generated by Django 5.0.3 on 2024-09-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semilleros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='contacto',
            field=models.CharField(default='Sin contacto', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semillero',
            name='docenteCoordinador',
            field=models.CharField(default='Sin docente', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semillero',
            name='programa',
            field=models.CharField(default='Sin programa', max_length=255),
            preserve_default=False,
        ),
    ]
>>>>>>> origin/juanGarzon
