# Generated by Django 5.0.3 on 2024-09-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semilleros', '0002_semillero_contacto_semillero_docentecoordinador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillero',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
