<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-09-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semilleros', '0003_semillero_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semillero',
            name='descripcion',
            field=models.TextField(default='Sin descripcion'),
        ),
    ]
=======
# Generated by Django 5.0.3 on 2024-09-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semilleros', '0003_semillero_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semillero',
            name='descripcion',
            field=models.TextField(default='Sin descripcion'),
        ),
    ]
>>>>>>> origin/juanGarzon
