# Generated by Django 5.0.3 on 2024-09-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos_estudiantiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='imagen',
            field=models.CharField(max_length=255),
        ),
    ]
